--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/09/2015 13:59:08
-- Server version: 5.6.26-log
-- Client version: 4.1
--


--
-- Definition for database rpgbd
--
DROP DATABASE IF EXISTS rpgbd;
CREATE DATABASE IF NOT EXISTS rpgbd
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE rpgbd;

--
-- Definition for table aneis
--
CREATE TABLE IF NOT EXISTS aneis (
  ID_anel INT(11) NOT NULL,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_anel)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table armaduras
--
CREATE TABLE IF NOT EXISTS armaduras (
  ID_armadura INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_armadura)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table armas
--
CREATE TABLE IF NOT EXISTS armas (
  ID_armas INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_armas)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table inventario
--
CREATE TABLE IF NOT EXISTS inventario (
  inv_id INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (inv_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table jogador
--
CREATE TABLE IF NOT EXISTS jogador (
  jog_id INT(11) NOT NULL AUTO_INCREMENT,
  jog_login VARCHAR(20) NOT NULL,
  jog_senha INT(10) NOT NULL,
  PRIMARY KEY (jog_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table status
--
CREATE TABLE IF NOT EXISTS status (
  sta_id INT(11) NOT NULL AUTO_INCREMENT,
  sta_forca INT(100) NOT NULL DEFAULT 0,
  sta_defesa INT(100) NOT NULL DEFAULT 0,
  sta_velocidade INT(100) NOT NULL DEFAULT 0,
  sta_inteligencia INT(100) NOT NULL DEFAULT 0,
  sta_magia INT(100) NOT NULL DEFAULT 0,
  sta_ataque INT(100) NOT NULL DEFAULT 0,
  sta_mp INT(100) NOT NULL DEFAULT 0,
  sta_mp_atual INT(100) NOT NULL DEFAULT 0,
  sta_hp INT(100) NOT NULL DEFAULT 0,
  sta_hp_atual INT(100) NOT NULL DEFAULT 0,
  PRIMARY KEY (sta_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table itens
--
CREATE TABLE IF NOT EXISTS itens (
  itens_id INT(11) NOT NULL AUTO_INCREMENT,
  itens_armas INT(11) DEFAULT 0,
  itens_armaduras INT(11) NOT NULL DEFAULT 0,
  itens_aneis INT(11) NOT NULL DEFAULT 0,
  itens_status INT(11) NOT NULL,
  PRIMARY KEY (itens_id),
  CONSTRAINT FK_itens_aneis_ID_anel FOREIGN KEY (itens_aneis)
    REFERENCES aneis(ID_anel) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_itens_armaduras_ID_armadura FOREIGN KEY (itens_armaduras)
    REFERENCES armaduras(ID_armadura) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_itens_armas_ID_armas FOREIGN KEY (itens_armas)
    REFERENCES armas(ID_armas) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_itens_status_sta_id FOREIGN KEY (itens_status)
    REFERENCES status(sta_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table mobs
--
CREATE TABLE IF NOT EXISTS mobs (
  mob_id INT(11) NOT NULL AUTO_INCREMENT,
  mob_nome VARCHAR(50) NOT NULL,
  mob_status INT(11) DEFAULT NULL,
  PRIMARY KEY (mob_id),
  CONSTRAINT FK_mobs_status_sta_id FOREIGN KEY (mob_status)
    REFERENCES status(sta_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table personagem
--
CREATE TABLE IF NOT EXISTS personagem (
  per_id INT(11) NOT NULL AUTO_INCREMENT,
  per_nome VARCHAR(20) NOT NULL,
  per_lvl INT(20) NOT NULL DEFAULT 0,
  per_status INT(11) NOT NULL,
  per_jogador INT(11) NOT NULL,
  per_inventario INT(11) NOT NULL,
  PRIMARY KEY (per_id),
  CONSTRAINT FK_per_inventario_inv_id FOREIGN KEY (per_inventario)
    REFERENCES inventario(inv_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_per_jogador_jog_id FOREIGN KEY (per_jogador)
    REFERENCES jogador(jog_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_per_status_sta_id FOREIGN KEY (per_status)
    REFERENCES status(sta_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table meu_iten
--
CREATE TABLE IF NOT EXISTS meu_iten (
  meu_id INT(11) NOT NULL,
  meu_inventario INT(11) DEFAULT NULL,
  meu_item INT(11) DEFAULT NULL,
  meu_quantidade INT(200) DEFAULT 0,
  PRIMARY KEY (meu_id),
  CONSTRAINT FK_meu_iten_inventario_inv_id FOREIGN KEY (meu_inventario)
    REFERENCES inventario(inv_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_meu_iten_itens_itens_id FOREIGN KEY (meu_item)
    REFERENCES itens(itens_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table aneis
--

-- Table rpgbd.aneis does not contain any data (it is empty)

-- 
-- Dumping data for table armaduras
--

-- Table rpgbd.armaduras does not contain any data (it is empty)

-- 
-- Dumping data for table armas
--

-- Table rpgbd.armas does not contain any data (it is empty)

-- 
-- Dumping data for table inventario
--

-- Table rpgbd.inventario does not contain any data (it is empty)

-- 
-- Dumping data for table jogador
--

-- Table rpgbd.jogador does not contain any data (it is empty)

-- 
-- Dumping data for table status
--

-- Table rpgbd.status does not contain any data (it is empty)

-- 
-- Dumping data for table itens
--

-- Table rpgbd.itens does not contain any data (it is empty)

-- 
-- Dumping data for table mobs
--

-- Table rpgbd.mobs does not contain any data (it is empty)

-- 
-- Dumping data for table personagem
--

-- Table rpgbd.personagem does not contain any data (it is empty)

-- 
-- Dumping data for table meu_iten
--

-- Table rpgbd.meu_iten does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;